version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:10.1.0-1.73.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /projects/ishiko/cpp/types
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/types/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Platform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/platform.git && cd platform/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/GNUmakefile && make
      - run:
          name: "Install test dependency: Ishiko/C++ Text"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/text.git && cd text/build/GNUmakefile && make
      - run:
          name: "Install test dependency: Ishiko/C++ Process"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Tests"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/tests.git && cd tests/core/build/GNUmakefile && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/types/tests/build/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/types/tests/build/GNUmakefile && ./IshikoTypesTests
